const fs = require('fs/promises');
const path = require('path');
const { fileURLToPath } = require('url');


const TARGET_URL = 'https://netboxlabscms.kinsta.cloud/wp-json/together/options';
// Output directory relative to this script's parent directory, then into src/components/global
const OUTPUT_DIR = path.resolve(__dirname, '../src/components/global');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'options.data.ts');

async function fetchAndSaveOptions() {
  try {
    console.log(`Fetching options from ${TARGET_URL}...`);
    const response = await fetch(TARGET_URL);
    if (!response.ok) {
      throw new Error(`Failed to fetch options: ${response.status} ${response.statusText}`);
    }
    const data = await response.json();
    console.log('Successfully fetched options data.');

    // Ensure the target directory exists
    await fs.mkdir(OUTPUT_DIR, { recursive: true });

    const fileContent = `// This file is auto-generated by scripts/fetchOptions.ts
// Do not edit this file manually.

/* eslint-disable */
// Disable ESLint for this auto-generated file to avoid issues with potentially complex data structures.

export const options = ${JSON.stringify(data, null, 2)} as const;
`;

    await fs.writeFile(OUTPUT_FILE, fileContent, 'utf-8');
    console.log(`Successfully saved options to ${OUTPUT_FILE}`);

  } catch (error) {
    console.error('Error fetching or saving options:', error);
    process.exit(1); // Exit with error code to fail the build
  }
}

fetchAndSaveOptions();