name: Disabled - Auto-merge for Documentation PRs

# This workflow has been disabled - functionality moved to auto-merge-docs.yml
# to avoid conflicts between multiple auto-merge attempts

on:
  workflow_dispatch: # Manual trigger only

jobs:
  disabled:
    runs-on: ubuntu-latest
    if: false  # Workflow disabled
    steps:
      - name: Disabled
        run: echo "This workflow is disabled - see auto-merge-docs.yml instead" 