// This file is auto-generated by scripts/fetchOptions.ts
// Do not edit this file manually.

/* eslint-disable */
// Disable ESLint for this auto-generated file to avoid issues with potentially complex data structures.

export const options = {
  "header": {
    "": null,
    "nav": {
      "items": [
        {
          "link": {
            "title": "Platform",
            "url": "/#",
            "target": ""
          },
          "has_submenu": true,
          "submenu": {
            "submenu_layout": "threeCol",
            "three_column_submenu": {
              "left_column": {
                "submenu_modules": [
                  {
                    "acf_fc_layout": "link_list",
                    "link_list": {
                      "subheading": "Products",
                      "links": [
                        {
                          "link": {
                            "title": "NetBox",
                            "url": "/netbox/",
                            "target": ""
                          },
                          "icon": {
                            "url": "https://netboxlabscms.kinsta.cloud/wp-content/uploads/2025/04/triangle-icon-2.svg",
                            "alt": "Triangle Icon 2",
                            "width": 23,
                            "height": 23
                          },
                          "description": "Make sense of your network."
                        },
                        {
                          "link": {
                            "title": "Discovery",
                            "url": "/netbox-discovery/",
                            "target": ""
                          },
                          "icon": {
                            "url": "https://netboxlabscms.kinsta.cloud/wp-content/uploads/2025/04/triangle-icon-2.svg",
                            "alt": "Triangle Icon 2",
                            "width": 23,
                            "height": 23
                          },
                          "description": "Accelerate documentation."
                        },
                        {
                          "link": {
                            "title": "Assurance",
                            "url": "/#",
                            "target": ""
                          },
                          "icon": {
                            "url": "https://netboxlabscms.kinsta.cloud/wp-content/uploads/2025/04/triangle-icon-2.svg",
                            "alt": "Triangle Icon 2",
                            "width": 23,
                            "height": 23
                          },
                          "description": "Eliminate operational drift."
                        }
                      ]
                    }
                  }
                ]
              },
              "middle_column": {
                "submenu_modules": [
                  {
                    "acf_fc_layout": "link_list",
                    "link_list": {
                      "subheading": "Deployment Options",
                      "links": [
                        {
                          "link": {
                            "title": "Cloud",
                            "url": "/netbox-cloud",
                            "target": ""
                          },
                          "icon": false,
                          "description": "A fully-hosted SaaS edition of NetBox."
                        },
                        {
                          "link": {
                            "title": "Enterprise",
                            "url": "/netbox-enterprise/",
                            "target": ""
                          },
                          "icon": false,
                          "description": "The power of NetBox in your own infra."
                        },
                        {
                          "link": {
                            "title": "Community",
                            "url": "/netbox-community/",
                            "target": ""
                          },
                          "icon": false,
                          "description": "The open source version of NetBox."
                        }
                      ]
                    }
                  }
                ]
              },
              "right_column": {
                "submenu_modules": [
                  {
                    "acf_fc_layout": "card_cta",
                    "card_cta": {
                      "link": {
                        "title": "Nitro AI",
                        "url": "/nitro-ai/",
                        "target": ""
                      },
                      "asset": {
                        "type": "image",
                        "image": {
                          "url": "https://netboxlabscms.kinsta.cloud/wp-content/uploads/2025/05/nitro-ai-nav-thumbnail.png",
                          "alt": "Nitro Ai Nav Thumbnail",
                          "width": 600,
                          "height": 438
                        },
                        "animation": {
                          "rive_file": false,
                          "aspect_ratio": ""
                        }
                      }
                    }
                  },
                  {
                    "acf_fc_layout": "link_list",
                    "link_list": {
                      "subheading": "",
                      "links": [
                        {
                          "link": {
                            "title": "Integrations",
                            "url": "/integrations/",
                            "target": ""
                          },
                          "icon": false,
                          "description": ""
                        },
                        {
                          "link": {
                            "title": "Plugins",
                            "url": "/plugins/",
                            "target": ""
                          },
                          "icon": false,
                          "description": ""
                        },
                        {
                          "link": {
                            "title": "Security",
                            "url": "/security",
                            "target": ""
                          },
                          "icon": false,
                          "description": ""
                        },
                        {
                          "link": {
                            "title": "Docs",
                            "url": "/#",
                            "target": "_blank"
                          },
                          "icon": false,
                          "description": ""
                        }
                      ]
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "link": {
            "title": "Solutions",
            "url": "/#",
            "target": ""
          },
          "has_submenu": true,
          "submenu": {
            "submenu_layout": "threeCol",
            "three_column_submenu": {
              "left_column": {
                "submenu_modules": [
                  {
                    "acf_fc_layout": "link_list",
                    "link_list": {
                      "subheading": "We help with",
                      "links": [
                        {
                          "link": {
                            "title": "Operations",
                            "url": "/operations/",
                            "target": ""
                          },
                          "icon": {
                            "url": "https://netboxlabscms.kinsta.cloud/wp-content/uploads/2025/04/triangle-icon-2.svg",
                            "alt": "Triangle Icon 2",
                            "width": 23,
                            "height": 23
                          },
                          "description": "Organize and model your network."
                        },
                        {
                          "link": {
                            "title": "Automation",
                            "url": "https://netboxlabs.bytogether.agency/automation/",
                            "target": ""
                          },
                          "icon": {
                            "url": "https://netboxlabscms.kinsta.cloud/wp-content/uploads/2025/04/traingle-icon-purple.svg",
                            "alt": "Traingle Icon Purple",
                            "width": 23,
                            "height": 23
                          },
                          "description": "Automate IPAM and DCIM with a NSoT."
                        },
                        {
                          "link": {
                            "title": "Observability",
                            "url": "/#",
                            "target": ""
                          },
                          "icon": {
                            "url": "https://netboxlabscms.kinsta.cloud/wp-content/uploads/2025/04/traingle-icon-blue.svg",
                            "alt": "Traingle Icon Blue",
                            "width": 23,
                            "height": 23
                          },
                          "description": "Keep track of network performance."
                        },
                        {
                          "link": {
                            "title": "Security",
                            "url": "/security",
                            "target": ""
                          },
                          "icon": {
                            "url": "https://netboxlabscms.kinsta.cloud/wp-content/uploads/2025/04/traingle-icon-orange.svg",
                            "alt": "Traingle Icon Orange",
                            "width": 23,
                            "height": 23
                          },
                          "description": "Identify and address vulnerabilities."
                        }
                      ]
                    }
                  }
                ]
              },
              "middle_column": {
                "submenu_modules": [
                  {
                    "acf_fc_layout": "link_list",
                    "link_list": {
                      "subheading": "What’s your infrastructure?",
                      "links": [
                        {
                          "link": {
                            "title": "Data Center Infrastructure",
                            "url": "/datacenter-infrastructure-management/",
                            "target": ""
                          },
                          "icon": false,
                          "description": "Manage and automate data center networks."
                        },
                        {
                          "link": {
                            "title": "Campus Networks",
                            "url": "/#",
                            "target": ""
                          },
                          "icon": false,
                          "description": "Get visibility into campus environments."
                        },
                        {
                          "link": {
                            "title": "Branch Networks",
                            "url": "/#",
                            "target": ""
                          },
                          "icon": false,
                          "description": "Simplify branch network operations."
                        },
                        {
                          "link": {
                            "title": "ISP & Telco Networks",
                            "url": "/#",
                            "target": ""
                          },
                          "icon": false,
                          "description": "Optimize service provider networks."
                        },
                        {
                          "link": {
                            "title": "Hybrid Cloud Infrastructure",
                            "url": "/#",
                            "target": ""
                          },
                          "icon": false,
                          "description": "Unify hybrid cloud environments."
                        },
                        {
                          "link": {
                            "title": "OT Infrastructure",
                            "url": "/#",
                            "target": ""
                          },
                          "icon": false,
                          "description": "Monitor and secure operational technology."
                        }
                      ]
                    }
                  }
                ]
              },
              "right_column": {
                "submenu_modules": [
                  {
                    "acf_fc_layout": "featured_resource",
                    "featured_resource": {
                      "subheading": "Featured",
                      "resource": false
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "link": {
            "title": "Resources",
            "url": "/#",
            "target": ""
          },
          "has_submenu": true,
          "submenu": {
            "submenu_layout": "threeCol",
            "three_column_submenu": {
              "left_column": {
                "submenu_modules": [
                  {
                    "acf_fc_layout": "link_list",
                    "link_list": {
                      "subheading": "Resources",
                      "links": [
                        {
                          "link": {
                            "title": "Blog",
                            "url": "/blog/",
                            "target": ""
                          },
                          "icon": false,
                          "description": "Discover the latest insights."
                        },
                        {
                          "link": {
                            "title": "eBooks",
                            "url": "/ebooks/",
                            "target": ""
                          },
                          "icon": false,
                          "description": "Download one of our guides."
                        },
                        {
                          "link": {
                            "title": "Events & Webinars",
                            "url": "/events/",
                            "target": ""
                          },
                          "icon": false,
                          "description": "Sign up for a NetBox event."
                        },
                        {
                          "link": {
                            "title": "Podcasts",
                            "url": "/podcasts/",
                            "target": ""
                          },
                          "icon": false,
                          "description": "Hear from industry experts."
                        },
                        {
                          "link": {
                            "title": "News",
                            "url": "/news/",
                            "target": ""
                          },
                          "icon": false,
                          "description": "Get the latest company updates."
                        },
                        {
                          "link": {
                            "title": "Customer Stories",
                            "url": "/customer-stories/",
                            "target": ""
                          },
                          "icon": false,
                          "description": "See how customers succeed with NetBox."
                        }
                      ]
                    }
                  }
                ]
              },
              "middle_column": {
                "submenu_modules": [
                  {
                    "acf_fc_layout": "link_list",
                    "link_list": {
                      "subheading": "Learn",
                      "links": [
                        {
                          "link": {
                            "title": "Training",
                            "url": "/netbox-training/",
                            "target": ""
                          },
                          "icon": false,
                          "description": "Learn and grow your NetBox skills."
                        },
                        {
                          "link": {
                            "title": "Tools to Champion NetBox",
                            "url": "/#",
                            "target": ""
                          },
                          "icon": false,
                          "description": "Equip yourself to advocate for NetBox."
                        },
                        {
                          "link": {
                            "title": "Docs",
                            "url": "/#",
                            "target": "_blank"
                          },
                          "icon": false,
                          "description": "Build and extend with developer resources."
                        }
                      ]
                    }
                  }
                ]
              },
              "right_column": {
                "submenu_modules": [
                  {
                    "acf_fc_layout": "featured_resource",
                    "featured_resource": {
                      "subheading": "Featured",
                      "resource": false
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "link": {
            "title": "Community",
            "url": "/netbox-community/",
            "target": ""
          },
          "has_submenu": true,
          "submenu": {
            "submenu_layout": "threeCol",
            "three_column_submenu": {
              "left_column": {
                "submenu_modules": [
                  {
                    "acf_fc_layout": "tile_cta",
                    "tile_cta": {
                      "link": {
                        "title": "The NetBox Community",
                        "url": "/netbox-community/",
                        "target": ""
                      },
                      "asset": {
                        "type": "image",
                        "image": {
                          "url": "https://netboxlabscms.kinsta.cloud/wp-content/uploads/2025/04/netbox-community-nav.svg",
                          "alt": "Netbox Community Nav",
                          "width": 348,
                          "height": 219
                        },
                        "animation": {
                          "rive_file": false,
                          "aspect_ratio": ""
                        }
                      },
                      "description": "Connect and collaborate with NetBox users."
                    }
                  }
                ]
              },
              "middle_column": {
                "submenu_modules": [
                  {
                    "acf_fc_layout": "link_list",
                    "link_list": {
                      "subheading": "",
                      "links": [
                        {
                          "link": {
                            "title": "Community Slack",
                            "url": "https://netdev.chat/",
                            "target": "_blank"
                          },
                          "icon": false,
                          "description": ""
                        },
                        {
                          "link": {
                            "title": "NetBox on GitHub",
                            "url": "https://github.com/netboxlabs",
                            "target": "_blank"
                          },
                          "icon": false,
                          "description": ""
                        }
                      ]
                    }
                  }
                ]
              },
              "right_column": {
                "submenu_modules": [
                  {
                    "acf_fc_layout": "featured_resource",
                    "featured_resource": {
                      "subheading": "Featured",
                      "resource": {
                        "ID": 341,
                        "post_title": "FOSDEM 2025",
                        "post_type": "event",
                        "permalink": "/events/fosdem-2025/",
                        "featured_image": {
                          "src": "https://netboxlabscms.kinsta.cloud/wp-content/uploads/2025/03/event-thumbnail.jpg",
                          "width": 760,
                          "height": 460
                        },
                        "acf": {
                          "event_details": {
                            "type": "Webinar",
                            "location": "London",
                            "dates": [
                              {
                                "date": "06/20/2025",
                                "time": "5 PM"
                              }
                            ]
                          }
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "link": {
            "title": "Pricing",
            "url": "/pricing/",
            "target": ""
          },
          "has_submenu": false,
          "submenu": {
            "submenu_layout": false,
            "three_column_submenu": {
              "left_column": {
                "submenu_modules": false
              },
              "middle_column": {
                "submenu_modules": false
              },
              "right_column": {
                "submenu_modules": false
              }
            }
          }
        },
        {
          "link": {
            "title": "Docs",
            "url": "/docs/netbox/",
            "target": ""
          },
          "has_submenu": false,
          "submenu": {
            "submenu_layout": false,
            "three_column_submenu": {
              "left_column": {
                "submenu_modules": false
              },
              "middle_column": {
                "submenu_modules": false
              },
              "right_column": {
                "submenu_modules": false
              }
            }
          }
        }
      ]
    },
    "ctas": {
      "primary_cta": {
        "title": "Start for free",
        "url": "/#",
        "target": ""
      },
      "secondary_cta": {
        "title": "Get a demo",
        "url": "/get-a-demo/",
        "target": ""
      }
    },
    "announcement_banner": {
      "icon": {
        "url": "https://netboxlabscms.kinsta.cloud/wp-content/uploads/2025/04/announcement-cube-icon.svg",
        "alt": "Announcement Cube Icon",
        "width": 24,
        "height": 24
      },
      "link": {
        "title": "Blog or learning piece, maybe some news |here|",
        "url": "/#",
        "target": ""
      },
      "homepage_only": true
    }
  },
  "footer": {
    "": null,
    "pre_footer_cta": {
      "heading": "Make sense of your network",
      "links": [
        {
          "link": {
            "link": {
              "title": "Start for free",
              "url": "/#",
              "target": ""
            },
            "type": "button",
            "button": {
              "": null,
              "type": "default",
              "background_color": "white"
            }
          }
        },
        {
          "link": {
            "link": {
              "title": "Get a demo",
              "url": "/get-a-demo/",
              "target": ""
            },
            "type": "button",
            "button": {
              "": null,
              "type": "default",
              "background_color": "grey-13"
            }
          }
        }
      ]
    },
    "nav": [
      {
        "heading": "Platform",
        "items": [
          {
            "link": {
              "title": "Cloud",
              "url": "/netbox-cloud/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Enterprise",
              "url": "/netbox-enterprise/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Community",
              "url": "/netbox-community/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "NetBox",
              "url": "/netbox/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Discovery",
              "url": "/netbox-discovery/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Assurance",
              "url": "#",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Integrations",
              "url": "/integrations/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Security",
              "url": "/security/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Nitro AI",
              "url": "/nitro-ai/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Docs",
              "url": "/docs/netbox/",
              "target": ""
            }
          }
        ]
      },
      {
        "heading": "Solutions",
        "items": [
          {
            "link": {
              "title": "Operations",
              "url": "/operations/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Automation",
              "url": "/#",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Observability",
              "url": "/#",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Security",
              "url": "/security/",
              "target": ""
            }
          }
        ]
      },
      {
        "heading": "Infrastructure",
        "items": [
          {
            "link": {
              "title": "Campus Networks",
              "url": "/#",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Data Centers",
              "url": "/datacenter-infrastructure-management/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Branch Networks",
              "url": "/#",
              "target": ""
            }
          },
          {
            "link": {
              "title": "ISP & Telco",
              "url": "/#",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Hybrid Cloud",
              "url": "/#",
              "target": ""
            }
          },
          {
            "link": {
              "title": "OT Infrastructure",
              "url": "/#",
              "target": ""
            }
          }
        ]
      },
      {
        "heading": "Resources",
        "items": [
          {
            "link": {
              "title": "Customer Stories",
              "url": "/customer-stories/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Blog",
              "url": "/blog/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Events & Webinars",
              "url": "/events/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "eBooks",
              "url": "/ebooks/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Champion NetBox",
              "url": "/#",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Pricing",
              "url": "/pricing/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "About",
              "url": "/about/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Careers",
              "url": "/careers/",
              "target": ""
            }
          },
          {
            "link": {
              "title": "Partners",
              "url": "/partners/",
              "target": ""
            }
          }
        ]
      }
    ],
    "ctas": [
      {
        "link": {
          "title": "netboxlabs.slack.com",
          "url": "https://netdev.chat/",
          "target": "_blank"
        },
        "icon": {
          "url": "https://netboxlabscms.kinsta.cloud/wp-content/uploads/2025/04/slack-icon.svg",
          "alt": "Slack Icon",
          "width": 22,
          "height": 23
        },
        "name": "Slack"
      },
      {
        "link": {
          "title": "netbox-community",
          "url": "https://github.com/netboxlabs",
          "target": "_blank"
        },
        "icon": {
          "url": "https://netboxlabscms.kinsta.cloud/wp-content/uploads/2025/04/github-icon.svg",
          "alt": "Github Icon",
          "width": 22,
          "height": 23
        },
        "name": "Github"
      }
    ],
    "newsletter_signup": {
      "heading": "Join the |NetBox Labs community.|",
      "": null
    },
    "legal": {
      "copyright_text": "Netbox Labs",
      "nav": [
        {
          "link": {
            "title": "Privacy Policy",
            "url": "/privacy-policy/",
            "target": ""
          }
        },
        {
          "link": {
            "title": "Terms of Use",
            "url": "/#",
            "target": ""
          }
        }
      ]
    }
  },
  "global": {
    "newsletter_signup": {
      "hubspot_form": {
        "heading": "Sign-up to be the first to know about NetBox news",
        "portal_id": "23319422",
        "form_id": "3cdf548c-e305-4932-99d4-f0729b3177b5"
      }
    },
    "resources": {
      "": null,
      "events": {
        "speakers_heading": "Featured Guest Speakers"
      },
      "news": {
        "thumbnail_fallback": {
          "url": "https://netboxlabscms.kinsta.cloud/wp-content/uploads/2025/05/news-thumbnail-fallback.png",
          "alt": "News Thumbnail Fallback",
          "width": 888,
          "height": 501
        }
      }
    }
  },
  "link_list": {
    "subheading": "",
    "links": false
  },
  "submenu_modules": false
} as const;
